---
title: "combining tpm and prediction for all samples"
output: html_document
date: "2025-02-18"
---

# Set up
```{r}
rm(list=ls())
library(tidyverse)
source("~/Documents/Projects/tutivia_AV_paper_2025/AV_Plots.R")
```

# Read in counts
```{r}
AllCounts<-read.csv("/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/FinalCounts.csv")%>%
  dplyr::select(-c("X"))%>%
  column_to_rownames(var="gene")

SampleInfo<-read.csv("/Users/alinaklineschoder/Desktop/AVSampleKey.csv")%>%
  filter(Sample.Name!="CP3_Batch_N16")

AllCounts<-AllCounts[include,]
```

### Table 1. FT 1 vs FT2
```{r}
FT_Meta<-SampleInfo%>%filter(Category=="RNAStabilityFT")%>%
  dplyr::select(Sample.Name,Control,Parameter)
FT_Counts<-AllCounts[,FT_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

FT<-left_join(FT_Counts,FT_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(FT2=100*sd(c(`2FT`,`1FT`))/mean(c(`2FT`,`1FT`)),
         FT1=100*sd(c(`1FT`,`1FT`))/mean(c(`1FT`,`1FT`)))%>%
  select(Gene,Control,FT2,FT1)%>%
  mutate(Type="RNA Stability - Freeze/Thaw")
```

### Table 2. Over 6mo/12mo
```{r}
Time_Meta<-SampleInfo%>%filter(Category=="RNAStabilityTime")%>%
  dplyr::select(Sample.Name,Control,Parameter)

Time_Counts<-AllCounts[,Time_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

Time<-left_join(Time_Counts,Time_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(
    `5d`=100*sd(c(T0,`5D`))/mean(c(T0,`5D`)),
    `15d`=100*sd(c(T0,`5D`,`17D`))/mean(c(T0,`5D`,`17D`)),
    `1mo`=100*sd(c(T0,`5D`,`17D`,`1M`))/mean(c(T0,`5D`,`17D`,`1M`)),
    `3mo`=100*sd(c(T0,`5D`,`17D`,`1M`,`3M`))/mean(c(T0,`5D`,`17D`,`1M`,`3M`)),
    `6mo`=100*sd(c(T0,`5D`,`17D`,`1M`,`3M`,`6M`))/mean(c(T0,`5D`,`17D`,`1M`,`3M`,`6M`)),
    `12mo`=100*sd(c(T0,`5D`,`17D`,`1M`,`3M`,`6M`,`12M`))/mean(c(T0,`5D`,`17D`,`1M`,`3M`,`6M`,`12M`)))%>%
  select(Gene,`15d`,`5d`,`1mo`,`3mo`,`6mo`,`12mo`,Control)%>%
  mutate(Type="RNA Stability - Time")
```

### Table 3. +/- DNASE
```{r}
DNAse_Meta<-SampleInfo%>%filter(Category=="Interference")%>%
  dplyr::select(Sample.Name,Control,Parameter)

DNAse_Counts<-AllCounts[,DNAse_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

DNAse<-left_join(DNAse_Counts,DNAse_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(WO_DNASE=100*sd(c(W,WO))/mean(c(W,WO)),
         W_DNASE=100*sd(c(W,W))/mean(c(W,W)))%>%
  select(Gene,WO_DNASE,W_DNASE,Control)%>%
  mutate(Type="Interference")

```

### Table 4. RNA Input
```{r}
RI_Meta<-SampleInfo%>%filter(Category=="RNAInput")%>%
  dplyr::select(Sample.Name,Control,Parameter)

RI_Counts<-AllCounts[,RI_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

RI<-left_join(RI_Counts,RI_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(RI400 = 100*sd(c(RI400,RI500))/mean(c(RI400,RI500)),
         RI600 = 100*sd(c(RI600,RI500))/mean(c(RI600,RI500)),
         RI720 = 100*sd(c(RI720,RI500))/mean(c(RI720,RI500)),
         RI320 = 100*sd(c(RI320,RI500))/mean(c(RI320,RI500)),
         RI500 = 100*sd(c(RI500,RI500))/mean(c(RI500,RI500)))%>%
  select(Gene,RI400,RI600,RI720,RI320,RI500,Control)%>%
  mutate(Type="RNA Input")
```
### Table 5. Library Input
```{r}
LI_Meta<-SampleInfo%>%filter(Category=="LibraryInput")%>%
  dplyr::select(Sample.Name,Control,Parameter)

LI_Counts<-AllCounts[,LI_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

LI<-left_join(LI_Counts,LI_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(LI6075 = 100*sd(c(LI6075,LI750))/mean(c(LI6075,LI750)),
         LI9075 = 100*sd(c(LI9075,LI750))/mean(c(LI9075,LI750)),
         LI675 = 100*sd(c(LI675,LI750))/mean(c(LI675,LI750)),
         LI825 = 100*sd(c(LI825,LI750))/mean(c(LI825,LI750)),
         LI750 = 100*sd(c(LI750,LI750))/mean(c(LI750,LI750))
         )%>%
  select(Gene,LI6075,LI9075,LI675,LI825,LI750,Control)%>%
  mutate(Type="Library Input")
```
### Table 6. Batch
```{r}
Batch_Meta<-SampleInfo%>%filter(Category=="Batch")%>%
  dplyr::select(Sample.Name,Control,Parameter)

Batch_Counts<-AllCounts[,Batch_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

Batch<-left_join(Batch_Counts,Batch_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(N25 = 100*sd(c(N25,N32))/mean(c(N25,N32)),
         N16 = 100*sd(c(N16,N32))/mean(c(N16,N32)),
         N64 = 100*sd(c(N64,N32))/mean(c(N64,N32)),
         N39 = 100*sd(c(N39,N32))/mean(c(N39,N32)),
         N32 = 100*sd(c(N32,N32))/mean(c(N32,N32)))%>%
  select(Gene,N25,N16,N64,N39,N32,Control)%>%
  mutate(Type="Batch Size")
```

### Table 7. Repeatability
```{r}
Repeat_Meta<-SampleInfo%>%filter(Category=="Repeatability")%>%
  dplyr::select(Sample.Name,Control,Parameter)%>%
  separate(col="Parameter",into = c("Grouping","Trash"),sep = "_")

Repeat_Counts<-AllCounts[,Repeat_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

Repeat<-left_join(Repeat_Counts,Repeat_Meta)%>%
  dplyr::select(-c(Sample.Name,Trash))%>%
  group_by(Grouping,Gene,Control)%>%
  summarize(Repeat=100*sd(value)/mean(value))%>%
  ungroup()%>%
  group_by(Gene,Control)%>%
  mutate(Mean=mean(Repeat))%>%
  select(Gene,Repeat,Mean,Control,Grouping)%>%
  mutate(Type="Repeatability")%>%
  pivot_wider(names_from = Grouping,values_from = Repeat)

```

### Table 8. Reproducibility
```{r}
Repro_Meta<-SampleInfo%>%filter(Category=="Reproducibility")%>%
  dplyr::select(Sample.Name,Control,Parameter)

Repro_Counts<-AllCounts[,Repro_Meta$Sample.Name]%>%
  rownames_to_column(var="Gene")%>%
  pivot_longer(cols=setdiff(colnames(.),"Gene"),names_to = "Sample.Name")

Repro<-left_join(Repro_Counts,Repro_Meta)%>%
  dplyr::select(-c(Sample.Name))%>%
  pivot_wider(names_from = Parameter,values_from = value)%>%
  rowwise()%>%
  mutate(Reproducibility=100*sd(c(L1R1,L2R1,L1R2,L2R2))/mean(c(L1R1,L2R1,L1R2,L2R2)))%>%
  select(Gene,Control,Reproducibility)%>%
  mutate(Type="Reproducibility")
```

## Combining All tables
```{r}
AllTabs<-bind_rows(FT,Time,DNAse,RI,LI,Batch,Repeat,Repro)%>%
  pivot_longer(cols=setdiff(colnames(.),c("Gene","Control","Type")))%>%
  filter(!is.na(value))

write.csv(AllTabs,"/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/CVs.csv")
```

## Plotting the chosen genes summary
```{r}




```
