---
title: "Score summary plots"
output: html_document
date: "2025-02-18"
---

# Set up
```{r}
rm(list=ls())
library(tidyverse)
source("~/Documents/Projects/AnalyticalValidation/AV_Plots.R")
```

# Read in scores
```{r}
AllScores<-read.csv("/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/FinalScores.csv")%>%
  dplyr::select(-c("X"))
Vec<-AllScores$Score
names(Vec)<-AllScores$Sample
SampleInfo<-read.csv("/Users/alinaklineschoder/Desktop/AVSampleKey.csv")

SampleInfo$Category<-gsub("RNAStabilityTime","RNA Stability - Storage Time",SampleInfo$Category)
SampleInfo$Category<-gsub("Interference","Library Preparation - Interference",SampleInfo$Category)
SampleInfo$Category<-gsub("RNAInput","Library Preparation - RNA Input",SampleInfo$Category)
SampleInfo$Category<-gsub("RNAStabilityFT","RNA Stability - Freeze/Thaw",SampleInfo$Category)
SampleInfo$Category<-gsub("LibraryInput","Sequencing Characterization - Library Input",SampleInfo$Category)
SampleInfo$Category<-gsub("Batch","Sequencing Characterization - Batch Size",SampleInfo$Category)

SampleInfo$Category<-factor(SampleInfo$Category,
                            levels=c("RNA Stability - Freeze/Thaw",
                                     "RNA Stability - Storage Time",
                                     "Library Preparation - Interference",
                                     "Library Preparation - RNA Input",
                                     "Sequencing Characterization - Library Input",
                                     "Sequencing Characterization - Batch Size",
                                     "Repeatability",
                                     "Reproducibility"))
```

## looking at all calculated scores per sample
```{r}
AllScores$Sample.Name=AllScores$Sample

Full<-left_join(AllScores,SampleInfo)


ggplot(Full, aes(x = Control, y = Score, color = Category)) +
  geom_jitter(width = 0.3) +
  stat_summary(fun = median, geom = "crossbar", width = 0.5, color = "black")+
  theme_minimal()+
  scale_color_manual(values=col)+
  theme(legend.title = element_blank())

```

## CV per control
```{r}
CV<-Full%>%
  group_by(Control)%>%
  summarize(CV=100*sd(Score)/mean(Score))
```


