---
title: "Score summary plots"
output: html_document
date: "2025-02-18"
---

# Set up CVs
```{r}
rm(list=ls())
library(tidyverse)
source("~/Documents/Projects/AnalyticalValidation/AV_Plots.R")

CVs<-read.csv("/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/CVs.csv")%>%
  filter(Gene%in%include)

CVs$name<-gsub("6mo","6 Months (0, 5d, 15d, 1mo, 3mo, 6mo)",CVs$name)
CVs$name<-gsub("12mo","12 Months (0, 5d, 15d, 1mo, 3mo, 6mo, 12mo)",CVs$name)


levs<-c("6 Months (0, 5d, 15d, 1mo, 3mo, 6mo)",
        "12 Months (0, 5d, 15d, 1mo, 3mo, 6mo, 12mo)")

CVs$name<-factor(CVs$name,
                 levels=c(levs,
                 setdiff(CVs$name,levs)))
```

# set up scores
```{r}
AllScores<-read.csv("/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/FinalScores.csv")%>%
  dplyr::select(-c("X"))
Vec<-AllScores$Score
names(Vec)<-AllScores$Sample
SampleInfo<-read.csv("/Users/alinaklineschoder/Desktop/AVSampleKey.csv")

SampleInfo$Category<-gsub("RNAStabilityTime","RNA Stability - Storage Time",SampleInfo$Category)
SampleInfo$Category<-gsub("Interference","Library Preparation - Interference",SampleInfo$Category)
SampleInfo$Category<-gsub("RNAInput","Library Preparation - RNA Input",SampleInfo$Category)
SampleInfo$Category<-gsub("RNAStabilityFT","RNA Stability - Freeze/Thaw",SampleInfo$Category)
SampleInfo$Category<-gsub("LibraryInput","Sequencing Characterization - Library Input",SampleInfo$Category)
SampleInfo$Category<-gsub("Batch","Sequencing Characterization - Batch Size",SampleInfo$Category)

SampleInfo$Category<-factor(SampleInfo$Category,
                            levels=c("RNA Stability - Freeze/Thaw",
                                     "RNA Stability - Storage Time",
                                     "Library Preparation - Interference",
                                     "Library Preparation - RNA Input",
                                     "Sequencing Characterization - Library Input",
                                     "Sequencing Characterization - Batch Size",
                                     "Repeatability",
                                     "Reproducibility"))

AllScores$Sample.Name=AllScores$Sample

Full<-left_join(AllScores,SampleInfo)

Full<-Full%>%
  separate(col = "Parameter",into = c("Parameter","trash"),sep = "_")
Full$Parameter<-gsub("FT","",Full$Parameter)
Full$Parameter<-gsub("12M","12mo",Full$Parameter)
Full$Parameter<-gsub("6M","6mo",Full$Parameter)
Full$Parameter<-gsub("3M","3mo",Full$Parameter)
Full$Parameter<-gsub("1M","1mo",Full$Parameter)
Full$Parameter<-gsub("17D","15d",Full$Parameter)
Full$Parameter<-gsub("5D","5d",Full$Parameter)
Full$Parameter<-gsub("RI","",Full$Parameter)
Full$Parameter<-gsub("LI","",Full$Parameter)
Full$Parameter<-gsub("WO","-DNAse",Full$Parameter)
Full$Parameter<-gsub("W","+DNAse",Full$Parameter)
Full$Parameter<-gsub("^N","",Full$Parameter)
levs<-c("T0","5d","15d","1mo","3mo","6mo","12mo","L1R1","L1R2","L2R1","L2R2","1", "2", "16","25", "32", "39", "64", "320", "400", "500", "600", "675", "720", "750", "825")
Full$Parameter<-factor(Full$Parameter,levels = c(levs,setdiff(Full$Parameter,levs)))

```


# Plotting and Saving
```{r}
### Freeze/Thaw
ggp1<-CVPlot(CVs %>% filter(Type == "RNA Stability - Freeze/Thaw"))
ggp2<-ScorePlot(Full %>% filter(Category == "RNA Stability - Freeze/Thaw"))+xlab("Freeze/Thaw (Count)")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none"),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))
ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/FT.png",bg="white",width = 10,height = 4)

### Storage Time
ggp1<-CVPlot(CVs %>% filter(Type == "RNA Stability - Time"))
ggp2<-ScorePlot(Full %>% filter(Category == "RNA Stability - Storage Time"))+xlab("-80\u00B0 Storage Time")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none",axis.text.x = element_text(size=8)),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))

ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/Time.png",bg="white",width = 10,height = 4)

### Interference
ggp1<-CVPlot(CVs %>% filter(Type == "Interference"))
ggp2<-ScorePlot(Full %>% filter(Category == "Library Preparation - Interference"))+
  xlab("Interference")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none"),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))
ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/Interference.png",bg="white",width = 10,height = 4)

### RNA Input
ggp1<-CVPlot(CVs %>% filter(Type == "RNA Input"))
ggp2<-ScorePlot(Full %>% filter(Category == "Library Preparation - RNA Input"))+
  xlab("RNA Input (ng)")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none"),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))
ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/RNAInput.png",bg="white",width = 10,height = 4)

### Library Input
ggp1<-CVPlot(CVs %>% filter(Type == "Library Input"))
ggp2<-ScorePlot(Full %>% filter(Category == "Sequencing Characterization - Library Input"))+
  xlab("Library Input (pM cDNA)")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none"),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))

ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/LibraryInput.png",bg="white",width = 10,height = 4)

### Batch Size
ggp1<-CVPlot(CVs %>% filter(Type == "Batch Size")%>%filter(name=="All"))
ggp2<-ScorePlot(Full %>% filter(Category == "Sequencing Characterization - Batch Size"))+
  xlab("Batch Size (N)")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none"),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))

ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/Batch.png",bg="white",width = 10,height = 4)

### Repeatability
ggp1<-CVPlot(CVs %>% filter(Type == "Repeatability"))+facet_grid(.~name)
ggsave(plot=ggp1,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/Repeatability.png",bg="white",width = 10,height = 4)

### Reproducibility
ggp1<-CVPlot(CVs %>% filter(Type == "Reproducibility"))+facet_grid(name~.)
ggp2<-ScorePlot(Full %>% filter(Category == "Reproducibility"))+
  xlab("Batch")
ggp<-cowplot::plot_grid(ggp1,ggp2+theme(legend.position = "none"),nrow=1,labels = c("A","B"),rel_widths = c(2.5,1))

ggsave(plot=ggp,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/Reproducibility.png",bg="white",width = 10,height = 4)


ggp2 <- ggplot(Full %>% filter(Category == "Repeatability"), 
               aes(y = Score, x = Parameter, color = Control, group = Control)) +
  geom_hline(yintercept = 50, linetype = "dashed", color = "red", size = 0.8) +
  stat_summary(geom = "pointrange", fun.data = mean_se) +  # or median_hilow if using median
  stat_summary(geom = "line", fun = mean) +
  scale_color_manual(values = col) + 
    ylim(0, 100) +
    # Labels for "High" and "Low"
    annotate("text", x = Inf, y = 100, label = "High Risk", hjust = 1.1, vjust = 1, 
             size = 3, fontface = "bold", color = "black") +
    annotate("text", x = Inf, y = 0, label = "Low Risk", hjust = 1.1, vjust = 0, 
             size = 3, fontface = "bold", color = "black")+ 
    ylab("Tutivia\u2122 Risk Score")+
    Paired_Theme+
  xlab("Batch")

ggsave(plot=ggp2,filename = "/Users/alinaklineschoder/Desktop/Data_AnalyticalValidation_Organized/Figures/Repeatability_Score.png",bg="white",width = 4,height = 4)
```

